name: Update
on:
  push: {}

  schedule:
    - cron:  '* 13 * * *'

jobs:
  build:
    name: Demo
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Updating stack
      uses: gimlet-io/gimlet-stack-updater-action@1dcc17067d9396d2e28abfa903e6807d360349f2
      with:
        config: 'fixture/stack.yaml'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
