name: Update
on:
  push: {}

  schedule:
    - cron:  '* 13 * * *'

jobs:
  build:
    name: Demo
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Updating stack
      uses: gimlet-io/gimlet-stack-updater-action@e3ebc0b07c951ce28dccd39e3d33604840285436
      with:
        config: 'fixture/stack.yaml'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
