name: Update
on:
  push: {}

  schedule:
    - cron:  '* 13 * * *'

jobs:
  build:
    name: Demo
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Updating stack
      uses: gimlet-io/gimlet-stack-updater-action@c839771e0e9eabc24e0f437a7179d7a7cc9210a1
      with:
        config: 'fixture/stack.yaml'
